name: stat_tool_dev
channels:
  - openalea3
  - conda-forge
dependencies:
  - scikit-build-core
  - setuptools_scm
  - cmake
  - boost
  - matplotlib-base
  - pip
  - pip:
      - -e '..[test,dev,doc]'
